[tool.poetry]
name = "ssu-plector-model"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["setuptools>=42", "wheel", "build<0.10.0"]
build-backend = "setuptools.build_meta"
