from enum import Enum


class Part(Enum):
    BACKEND = "BACKEND"
    MIDDLE_TIER = "MIDDLE_TIER"
    WEB = "WEB"
    IOS = "IOS"
    ANDROID = "ANDROID"
    DESKTOP = "DESKTOP"
    MOBILE = "MOBILE"
    GRAPHICS = "GRAPHICS"
    GAME = "GAME"
    DATA_SCIENTIST = "DATA_SCIENTIST"
    BIG_DATA = "BIG_DATA"
    DEVOPS = "DEVOPS"
    SOFTWARE_TEST = "SOFTWARE_TEST"
    EMBEDDED_SOFTWARE = "EMBEDDED_SOFTWARE"
    SECURITY = "SECURITY"
